console.log(1==1)// output true
console.log(undefined==null) // null ko hamesha undefined visa-versa se compare kroge to true hi milega 
console.log(["s"]=="s") // array convert to string by js so it will become "s"="s"->true
console.log([22]==22)// same this convert to string and give true
console.log(null==0)//false null ko agar undefined ko chod kisi or se compare kroge to hamesha false milega
console.log(null>0) //false  //greater than or equal to less than equal to convert varibale to number and then compare 0>0 false
console.log(null<0)//false
console.log(null>=0)//true
console.log(null<=0)//true
// output
// true
// true
// true
// true
// false
// false
// false
// true
// true


